### ISSUE TITLE
Is this project "dead"?

### ISSUE THREAD

**Issue by garyffh** [NativeScript/nativescript-remote-builds#16]
Is this project dead - is there an alternative for cloud builds?

**Comment by NathanaelA** [comment]
Nope, it isn't.

**Comment by NathanaelA** [comment]
Nope, it isn't Dead. 

At this point we don't offer any cloud builds; but you can use several third parties to do cloud builds using this plugin.

**Comment by leocrawf** [comment]
@NathanaelA can you recommend one that works well with the plugin?

**Comment by NathanaelA** [comment]
Depends on what you are planning on doing, You can use GitHub Actions, or Circle CI
